<?php
echo "<h1>Hello User Welcome</h1>";
echo PHP_EOL;
echo $this->tag->linkTo(['signup',$this->locale->_('Signup Here!'), 'class' => 'm-3 btn btn-primary']);
echo $this->tag->linkTo(['product',$this->locale->_('Add products Here!'), 'class' => 'm-3 btn btn-primary']);
echo $this->tag->linkTo(['order',$this->locale->_('Place Order Here!'), 'class' => 'm-3 btn btn-primary']);
echo $this->tag->linkTo(['setting',$this->locale->_('Apply Settings Here!'), 'class' => 'm-3 btn btn-primary']);
echo $this->tag->linkTo(['role',$this->locale->_('Add role Here!'), 'class' => 'm-3 btn btn-primary']);
echo $this->tag->linkTo(['addaction',$this->locale->_('Add action Here!'), 'class' => 'm-3 btn btn-primary']);
