<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<!-- main section for Orders  -->

<body>
    <?php
    echo $this->tag->linkTo(['signup', $this->locale->_('Signup Here!'), 'class' => 'm-3 btn btn-primary']);
    echo $this->tag->linkTo(['product', $this->locale->_('Add products Here!'), 'class' => 'm-3 btn btn-primary']);
    echo $this->tag->linkTo(['order', $this->locale->_('Place Order Here!'), 'class' => 'm-3 btn btn-primary']);
    echo $this->tag->linkTo(['setting', $this->locale->_('Apply Settings Here!'), 'class' => 'm-3 btn btn-primary']);
    echo $this->tag->linkTo(['role', $this->locale->_('Add role Here!'), 'class' => 'm-3 btn btn-primary']);
    echo $this->tag->linkTo(['addaction', $this->locale->_('Add action Here!'), 'class' => 'm-3 btn btn-primary']);
    echo  $this->tag->linkTo(['product/view', $this->locale->_('View Products'), 'class' => 'm-3 btn btn-primary']);
    echo  $this->tag->linkTo(['index', $this->locale->_('Homepage'), 'class' => 'm-3 btn btn-primary']);
    echo  $this->tag->linkTo(['order/show', $this->locale->_('View Orders'), 'class' => 'btn btn-primary']);

    ?>
    <h2>
    <?php echo $this->locale->_('Add Orders') ?>
</h2>
    <?php echo $this->tag->form("order/add"); ?>
    <p>
        <label for="customer_name"><?php echo $this->locale->_('customer-name') ?></label>
        <?php echo $this->tag->textfield(["customer_name", "class" => "form-control"]); ?>
    </p>
    <p>
        <label for="customer_address"><?php echo $this->locale->_('customer-address') ?> </label>
        <?php echo $this->tag->textfield(["customer_address", "class" => "form-control"]); ?>
    </p>
    <p>
        <label for="zipcode"><?php echo $this->locale->_('zipcode') ?></label>
        <?php echo $this->tag->textfield(["zipcode", "class" => "form-control"]); ?>
    </p>
    <p>
        <label for="product_name"><?php echo $this->locale->_('product-name') ?></label>
        <?php
        $product = $this->db->fetchAll(
            "SELECT * FROM products",
            \Phalcon\Db\Enum::FETCH_ASSOC
        );
        echo "   <select name='products' class='products'>";
        foreach ($product as $key => $value) {
            echo   "<option value=" . $value['name'] . ">" . $value['name'] . "</option>";
        }
        echo "</select>";
        ?>
    </p>
    <p>
        <label for="quantity"><?php echo $this->locale->_('quantity') ?></label>
        <?php echo $this->tag->textfield(["quantity", "class" => "form-control"]); ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton(["Place Order", 'class' => 'btn btn-primary']); ?>
    </p>

    </form>
</body>

</html>