<?php
echo $this->tag->linkTo(['product', 'Add products Here!', 'class' => 'm-3 btn btn-primary']);
echo $this->tag->linkTo(['order', 'Place Order Here!', 'class' => 'm-3 btn btn-primary']);
echo $this->tag->linkTo(['setting', 'Apply Settings Here!', 'class' => 'm-3 btn btn-primary']);
echo  $this->tag->linkTo(['index', 'Homepage', 'class' => 'm-3 btn btn-primary']);

echo "<table class= table table-striped >
        <thead>
            <th>ID</th>
            <th>Customer-Name</th>
            <th>Customer-Address</th>
            <th>Zipcode</th>
            <th>Product-name</th>
            <th>Quantity</th>
        </thead>
        <tbody>";
foreach ($result as $key => $value) {
    echo "<tr><td>" . $value['id'] . "</td><td>" . $value['customer_name'] . "</td><td>" . $value['customer_address'] .
        "</td><td>" . $value['zipcode'] . "</td><td>" . $value['product_name'] . "</td><td>" . $value['quantity'] .
        "</td></tr>";
}
echo "</tbody></table>";
